# Generated by Django 5.0.4 on 2024-05-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vulnérabilité', models.TextField(max_length=200)),
                ('Menaces', models.TextField(max_length=200)),
                ('Risque', models.TextField(max_length=200)),
                ('Probabilité_occurrence', models.FloatField(max_length=200)),
                ('Impact_C', models.FloatField(max_length=200)),
                ('Impact_I', models.FloatField(max_length=200)),
                ('Impact_D', models.FloatField(max_length=200)),
                ('Criticité', models.FloatField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('Valeur_unitaire_actif', models.IntegerField()),
                ('Coût_installation', models.IntegerField()),
                ('Coût_entretien', models.IntegerField()),
                ('VA', models.IntegerField()),
                ('Valeur_indisponibilité', models.IntegerField()),
            ],
        ),
    ]
