# Generated by Django 5.0.4 on 2024-05-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_risques', '0002_alter_analyse_menaces_alter_analyse_risque_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='Coût_entretien',
            new_name='Cout_entretien',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='Coût_installation',
            new_name='Cout_installation',
        ),
    ]
