# Generated by Django 5.0.4 on 2024-05-09 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_risques', '0003_rename_coût_entretien_asset_cout_entretien_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeActif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': "Type d'actif",
            },
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': 'Actif'},
        ),
        migrations.AlterField(
            model_name='asset',
            name='actif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse_risques.typeactif'),
        ),
    ]
