# Generated by Django 5.0.4 on 2024-05-09 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_risques', '0009_alter_analyse_vulnérabilité'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='actif',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='analyse_risques.asset'),
            preserve_default=False,
        ),
    ]
