# Generated by Django 5.0.4 on 2024-05-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_risques', '0010_analyse_actif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyse',
            old_name='Criticité',
            new_name='criticite',
        ),
        migrations.RenameField(
            model_name='analyse',
            old_name='Impact_C',
            new_name='impact_c',
        ),
        migrations.RenameField(
            model_name='analyse',
            old_name='Impact_D',
            new_name='impact_d',
        ),
        migrations.RenameField(
            model_name='analyse',
            old_name='Impact_I',
            new_name='impact_i',
        ),
        migrations.RenameField(
            model_name='analyse',
            old_name='Menaces',
            new_name='menaces',
        ),
        migrations.RenameField(
            model_name='analyse',
            old_name='Risque',
            new_name='misque',
        ),
        migrations.RenameField(
            model_name='analyse',
            old_name='Probabilité_occurrence',
            new_name='probabilite_occurrence',
        ),
        migrations.RenameField(
            model_name='analyse',
            old_name='Vulnérabilité',
            new_name='vulnerabilite',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='Cout_entretien',
            new_name='cout_entretien',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='Cout_installation',
            new_name='cout_installation',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='VA',
            new_name='va',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='Valeur_indisponibilité',
            new_name='valeur_indisponibilite',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='Valeur_unitaire_actif',
            new_name='valeur_unitaire_actif',
        ),
    ]
