# Generated by Django 5.0.4 on 2024-05-26 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_risques', '0014_menace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='menaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analyse_risques.menace'),
        ),
    ]
