# Generated by Django 5.0.4 on 2024-05-27 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_risques', '0015_alter_analyse_menaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vunlerabilite',
            name='type_actif',
        ),
        migrations.AddField(
            model_name='vunlerabilite',
            name='code_cve',
            field=models.CharField(default='CVE-2021-1234', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menace',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActifMenace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse_risques.asset')),
                ('menace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyse_risques.menace')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='menaces',
            field=models.ManyToManyField(through='analyse_risques.ActifMenace', to='analyse_risques.menace'),
        ),
    ]
