# Generated by Django 5.0.4 on 2024-05-27 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_risques', '0016_remove_vunlerabilite_type_actif_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Analyse',
            new_name='EvaluationRisque',
        ),
    ]
