# Generated by Django 5.0.4 on 2024-06-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_risques', '0017_rename_analyse_evaluationrisque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationrisque',
            name='criticite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='evaluationrisque',
            name='impact_c',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='evaluationrisque',
            name='impact_d',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='evaluationrisque',
            name='impact_i',
            field=models.IntegerField(),
        ),
    ]
