# Generated by Django 5.0.3 on 2024-06-07 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_risques', '0018_alter_evaluationrisque_criticite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_domaine', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='evaluationrisque',
            name='facteur_exposition',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='evaluationrisque',
            name='sle',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vunlerabilite',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analyse_risques.domaine'),
        ),
    ]
