# Generated by Django 5.0.3 on 2024-06-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyse_risques', '0020_alter_evaluationrisque_facteur_exposition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationrisque',
            name='criticite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationrisque',
            name='impact_c',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationrisque',
            name='impact_d',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationrisque',
            name='impact_i',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
